const en_US = {
  SITE_TITLE: `Community Resource Explorer`,
  TEA_ID: `TEA identification number`,
  TERM_SCHOOL: `school`,
  BUTTON_VIEW_FEEDER: `Toggle feeder view`,
  BUTTON_VIEW_MAP: `Toggle map view`,
  BUTTON_MENU: `Menu`,
  BUTTON_SEARCH: `Select to search`,
  INPUT_SEARCH: `Search for a Dallas ISD school`,
  INPUT_PLACEHOLDER_SEARCH: `Search... `,
  LINK_OPEN_FILTER_PANEL: `(change)`,
  BUTTON_TOGGLE_PANEL_FILTERS: `Toggle filters panel`,
  BUTTON_TOGGLE_PANEL_WEIGHT: `Toggle weights panel`,
  BUTTON_TOGGLE_PANEL_INFO: `Toggle info panel`,
  BUTTON_SHARE_TWITTER: `Share on Twitter`,
  DIALOG_SHARE_TWITTER: `All Dallas neighborhoods should have what they need to thrive.`,
  BUTTON_SHARE_FACEBOOK: `Share on Facebook`,
  BUTTON_SHARE_EMAIL: `Share via email`,
  BUTTON_SHARE_LINK: `Get a custom link`,
  DIALOG_SHARE_EMAIL_SUBJECT: `CPAL Resource Explorer`,
  DIALOG_SHARE_EMAIL_BODY: `All Dallas neighborhoods should have what they need to thrive. Use the CPAL Resource Explorer to see how schools benefit from local resources: `,
  MODAL_SHARE_LINK_HEAD: `Share a Link`,
  MODAL_SHARE_LINK_INSTR: `Copy the link below to share the current view of the Explorer.`,
  MODAL_SHARE_LINK_INPUT: `Current View URL`,
  BTN_CLOSE: `Close`,
  UI_MAP_BUTTON_RESET_FILTER: `Reset active filter`,
  UI_MAP_FILTER_INSTRUCTIONS: `<p>Click the buttons below to select metrics and filter by quintile(s). Clear filters by pressing the "reset" {icon} button above.</p>`,
  SELECT_VIEW: `Select a view`,
  SELECT_ITEM_MAP: `Map view`,
  SELECT_ITEM_FEEDER: `Feeder view`,
  UI_MAP_SR:
    'Map of Dallas, with colors showing {metric} for {quintiles}.',
  UI_MAP_RESET: `Reset map`,
  UI_MAP_CAPTURE: `Screenshot map`,
  UI_MAP_CITY: `Dallas`,
  UI_MAP_LEGEND_TITLE: `Selected index:`,
  UI_MAP_TOGGLE_LAYERS: `TOGGLE LAYERS`,
  UI_MAP_LEGEND_SCHOOL_DOT: `School`,
  UI_MAP_LEGEND_SCHOOL_ZONE: `School zone (2 mile radius)`,
  UI_MAP_LAYERS_REDLINING: `Historical redlining`,
  UI_MAP_LAYERS_REDLINING_TIP: `Neighborhood zones created for the purpose of discriminatory lending and resource distribution. <a href="/faq/" target="_blank">See FAQ page for more.</a>`,
  UI_MAP_LAYERS_DISTRICTS: `District boundaries`,
  // UI_MAP_METRIC_TITLE_CRI: `Weighted Community Resource Index`,
  UI_MAP_METRIC_ABBREV_CRI: `CRI`,
  UI_MAP_METRIC_TITLE_CRI: `Community Resource Index`,
  UI_MAP_METRIC_DESC_CRI: `<p>The Community Resource Index is an average of all Index categories (economics, education, family, health, and community). It presents an overall view of the resources available to each school’s surrounding community.</p>`,
  UI_MAP_METRIC_TITLE_ECON: `Economics`,
  UI_MAP_METRIC_DESC_ECON: `<p>Weighted (0-100) Index of economic indicator variables, used to describe overall state of economic background in a campus neighborhood</p>`,
  UI_MAP_METRIC_TITLE_EDU: `Education`,
  UI_MAP_METRIC_DESC_EDU: `<p>Weighted (0-100) Index of education indicator variables, used to describe overall state of education background in a campus neighborhood</p>`,
  UI_MAP_METRIC_TITLE_FAM: `Family`,
  UI_MAP_METRIC_DESC_FAM: `<p>Weighted (0-100) Index of family indicator variables, used to describe overall state of family background in a campus neighborhood</p>`,
  UI_MAP_METRIC_TITLE_HEAL: `Health`,
  UI_MAP_METRIC_DESC_HEAL: `<p>Weighted (0-100) Index of health indicator variables, used to describe overall state of family background in a campus neighborhood</p>`,
  UI_MAP_METRIC_TITLE_COMM: `Community`,
  UI_MAP_METRIC_DESC_COMM: `<p>Weighted (0-100) index of community indicator variables, used to describe overall state of community background in a campus neighborhood</p>`,
  UI_MAP_METRIC_TITLE_ECON_INDEX: `Economics Index`,
  UI_MAP_METRIC_TITLE_EDU_INDEX: `Education Index`,
  UI_MAP_METRIC_TITLE_FAM_INDEX: `Family Index`,
  UI_MAP_METRIC_TITLE_HEAL_INDEX: `Health Index`,
  UI_MAP_METRIC_TITLE_COMM_INDEX: `Community Index`,
  UI_MAP_METRIC_TITLE_COMM_BBP: `Households with Broadband Access (%)`,
  UI_MAP_METRIC_COMM_BVP: `Overall Business Vacancies (%)`,
  UI_MAP_METRIC_COMM_CCTRCAP: `Community and Recreation Centers, per 10,000 Residents`,
  UI_MAP_METRIC_COMM_INCARPCT: `Adults Incarcerated (%)`,
  UI_MAP_METRIC_COMM_JUVCRIMECAP: `Juvenile-Committed Violent Crime, per 10,000 Residents Under 18`,
  UI_MAP_METRIC_COMM_LIBCAP: `Libraries, per 10,000 Residents`,
  UI_MAP_METRIC_COMM_LTBVP: `Long-Term Business Vacancies (%)`,
  UI_MAP_METRIC_COMM_LTRVP: `Long-Term Residential Vacancies (%)`,
  UI_MAP_METRIC_COMM_OCB: `Owner-occupied households that are cost burdened`,
  UI_MAP_METRIC_COMM_OCBP: `Owner-Occupied and Cost-Burdened Households (%)`,
  UI_MAP_METRIC_COMM_PARKCAP: `Park Area (m2) per 10,000 Residents`,
  UI_MAP_METRIC_COMM_RCB: `Renter occupied households that are cost burdened`,
  UI_MAP_METRIC_COMM_RCBP: `Renter-Occupied and Cost-Burdened Households (%)`,
  UI_MAP_METRIC_COMM_RVP: `Overall Residential Vacancies (%)`,
  UI_MAP_METRIC_COMM_U18BBP: `Children Under 18 with Broadband Access (%)`,
  UI_MAP_METRIC_COMM_EVRATE: `Number of Evictions, per 10,000 Residents`,
  UI_MAP_METRIC_ECON_CPR: `Child Poverty Rate (%)`,
  UI_MAP_METRIC_ECON_FINCAP: `Banks and Credit Unions, per 10,000 Residents`,
  UI_MAP_METRIC_ECON_MEDINC: `Median Household Income`,
  UI_MAP_METRIC_ECON_PAYDAYCAP: `Payday Lending and Cash Advance Businesses, per 10,000 Residents`,
  UI_MAP_METRIC_ECON_PCTLWJOBS: `Jobs Earning less than $1,500 a Month (%)`,
  UI_MAP_METRIC_ECON_PCTMWJOBS: `Jobs Earning Between $1,500 and $3,333 a Month (%)`,
  UI_MAP_METRIC_ECON_PR: `Poverty Rate`,
  UI_MAP_METRIC_ECON_PYR: `Youth (16-24) Unemployment Rate (%)`,
  UI_MAP_METRIC_ECON_UR: `Unemployment Rate`,
  UI_MAP_METRIC_EDU_OOSTKIDS: `Afterschool Program Seats, per 10,000 Children under 5`,
  UI_MAP_METRIC_EDU_PERBACH: `Population with a Bachelor's Degree or Higher (%)`,
  UI_MAP_METRIC_EDU_PEREARLYED: `Children 3-4 Enrolled in School (%)`,
  UI_MAP_METRIC_EDU_QECKIDS: `High Quality Early Child Care Seats, per 10,000 Children under 5`,
  UI_MAP_METRIC_ECON_TOTJOBS: `Total Number of Jobs`,
  UI_MAP_METRIC_FAM_AFFCCKIDS: `Licensed Affordable Child Care Centers, per 10,000 Children Under 5`,
  UI_MAP_METRIC_FAM_LCCKIDS: `Licensed Child Care Centers, per 10,000 Children Under 5`,
  UI_MAP_METRIC_FAM_TPHH: `Two-parent households`,
  UI_MAP_METRIC_FAM_TPHHPCT: `Two-Parent Households (%)`,
  UI_MAP_METRIC_HEL_BPHIGH: `Adults with High Blood Pressure, per 10,000 Residents`,
  UI_MAP_METRIC_HEL_CASTTHMA: `Adults with Asthma, per 10,000 Residents`,
  UI_MAP_METRIC_HEL_CHECKUP: `Routine Doctor Visits, per 10,000 Residents`,
  UI_MAP_METRIC_HEL_FRUITSVEGGIES: `Combined Spending on Fresh Fruits and Vegetables`,
  UI_MAP_METRIC_HEL_LE: `Average Life Expectancy`,
  UI_MAP_METRIC_HEL_MHLTH: `Adults Reporting Poor Mental Health for 14 Days or More, per 10,000 Residents`,
  UI_MAP_METRIC_HEL_OBESITY: `Adult Obesity, per 10,000 Residents`,
  UI_MAP_METRIC_HEL_PERPRI: `Population with Private Health Insurance (%)`,
  UI_MAP_METRIC_HEL_PERPUB: `Population with Public Health Insurance (%)`,
  UI_MAP_METRIC_HEL_PHARMACAP: `Licensed Pharmacies, per 10,000 Residents`,
  UI_MAP_METRIC_HEL_PHLTH: `Adults with Poor Physical Health, per 10,000 Residents`,
  UI_MAP_METRIC_HEL_SLEEP: `Adults Sleeping less than 7 hours per Night, per 10,000 Residents`,
  UI_MAP_METRIC_HEL_STROKE: `Adults who have had a Stroke, per 10,000 Residents`,
  UI_MAP_METRIC_HEL_CLINCAP: `Number of Clinics, per 10,000 Residents`,
  UI_MAP_METRIC_HEL_GROCCAP: `Number of Grocery Stores, per 10,000 Residents`,
  UI_MAP_METRIC_HEL_PRTOPU: `Not available`,
  UI_MAP_METRIC_HEL_PERINS: `Population with Health Insurance (%)`,
  UI_MAP_METRIC_HEL_PERUNIN: `Population without Health Insurance (%)`,
  UI_FEEDER_TITLE_FEEDER_CHART: `Dallas ISD School Feeder Patterns`,
  UI_PANEL_INFO_FEEDER_DESC: `<h3>About the Feeder Pattern View</h3><p>A feeder pattern is the sequence of schools a student attends as they advance from grade to grade, based on their residing address.</p><p>The first chart shows each feeder pattern’s average Community Resource Index on a scale from 0-100.</p><p>The second chart shows the distribution of campuses across the range of the Community Resource Index.</p>`,
  UI_FEEDER_TITLE_FEEDER_DESC: `<p>Hover and click within the charts to see more data about each feeder pattern and its schools. You can also use the search bar to find a school and highlight its feeder pattern and campus.</p>`,
  UI_FEEDER_TITLE_SCHOOLS_CHART: `Distribution of campuses across CRI`,
  UI_FEEDER_TOOLTIP_INDEX_DESC: `*Index scores measured 0 to 100`,
  UI_FEEDER_TOOLTIP_SUBINDEX_AVG: `Average {metric} index score:`,
  UI_FEEDER_FEEDER_CHART_DESC: `Bar chart indicating average CRI for each feeder in Dallas ISD.`,
  UI_FEEDER_SCHOOL_CHART_DESC: `Scatterplot chart indicating number of schools with a given CRI value. Schools are highlighted when their feeder is hovered in the feeder chart.`,
  UI_MAP_TOOLTIP_FEEDER: `{name} Schools`,
  TERM_INDEX_AVERAGE: `Index Average`,
  TERM_PLURAL: `{term}s`,
  UI_MAP_PANEL_HEADING: `Index selection & filtering`,
  UI_MAP_PANEL_SELECT: `Select index category`,
  UI_MAP_PANEL_SELECT_QUINTILE: `Select quintile`,
  UI_MAP_PANEL_QUINTILE_0: `First quintile`,
  UI_MAP_PANEL_QUINTILE_1: `Second quintile`,
  UI_MAP_PANEL_QUINTILE_2: `Third quintile`,
  UI_MAP_PANEL_QUINTILE_3: `Fourth quintile`,
  UI_MAP_PANEL_QUINTILE_4: `Fifth quintile`,
  UI_MAP_PANEL_QUINTILE_ENABLE: `Enable {quintile} quintile`,
  UI_MAP_PANEL_QUINTILE_DISABLE: `Disable {quintile} quintile`,
  UI_MAP_PANEL_METRIC_ENABLE: `Enable metric {metric}`,
  UI_MAP_PANEL_METRIC_DISABLE: `Disable metric {metric}`,
  FIRST: `first`,
  SECOND: `second`,
  THIRD: `third`,
  FOURTH: `fourth`,
  FIFTH: `fifth`,
  ALL_FIVE: `all five`,
  QUINTILE: `quintile`,
  QUINTILES: `quintiles`,
  NO: `no`,
  AND: `and`,
  UI_CONTROL_PANEL_VIEW: `View`,
  UI_CONTROL_PANEL_VIEW: `Filter`,
  UI_CONTROL_PANEL_VIEW: `Share`,
  UI_MAP_METRIC_DEM_TOTP: `Total Population`,
  UI_MAP_METRIC_DEM_POPWH: `White, Non-Hispanic Population`,
  UI_MAP_METRIC_DEM_POPBL: `Black, Non-Hispanic Population`,
  UI_MAP_METRIC_DEM_POPAS: `Asian, Non-Hispanic Population`,
  UI_MAP_METRIC_DEM_POPHI: `Hispanic Population, All Races`,
  UI_MAP_METRIC_DEM_POPM: `Male Population, All Ages`,
  UI_MAP_METRIC_DEM_POPF: `Female Population, All Ages`,
  UI_MAP_METRIC_DEM_THH: `Total Households`,
  UI_MAP_METRIC_DEM_POPSE: `Senior Population (65 and Over)`,
  UI_MAP_METRIC_DEM_POPCH: `Child Population (Under 18)`,
  UI_PANEL_INFO_MAP: `<h5>Exploring in the map view</h5>

  <p>The map displays 189 Dallas ISD schools, each color-coded to show their score within the metrics that make up the Community Resource Index. The color scale has 5 blocks, each representing a quintile within the scale. The lighter the color, the higher the score.</p>
  
  <p>You can change the metric shown on the map by clicking the METRICS button and making selections. You can also use this feature to filter schools on the map by quintiles.</p>
  
  <p>To see the entire list of metrics for a school, click its dot on the map. A full report about this school will appear in a new tab in your browser.</p>
  
  <p>Use the “toggle map layers” feature to see historical redlining zones (<a href="/faq/#use-2" target="_blank">see FAQ for more</a>) and toggle district boundaries on and off.</p>
  
  <p>You can also grab a snapshot of your screen using the camera button, and share a custom link to your current Explorer view via the SHARE buttons.</p>
  
  <p>Questions? Visit our <a href="/faq" target="_blank">FAQ</a>.</p>`,
  UI_PANEL_INFO_FEEDER: `<h5>Exploring in the Feeder Pattern View</h5><p>A feeder pattern is the sequence of schools a student attends as they advance from grade to grade, based on where they live.</p><p>The first chart shows each feeder pattern’s average Community Resource Index on a scale from 0-100.</p><p>The second chart shows the distribution of campuses across the range of the Community Resource Index.</p> <p>Hover and click within the charts to see more data about each feeder pattern and its schools. You can also use the search bar to find a school and highlight its feeder pattern and campus.</p>`,
  UI_MAP_CLICK_SCHOOL_PROMPT: `Click on school to view full report.`,
  UI_MAP_SCHOOL_ACCESS_LINK: `Access full report.`,
  UI_MAP_FLY_TO_PROMPT: `Hover school for more information, or click
  school to see a detailed report.`,
  UI_MAP_INTRO_MODAL_HEADER: `Welcome to the Community Resource Explorer`,
  UI_MAP_INTRO_MODAL_INTRO: `The map and charts in this tool allow users to learn about resource distribution in the Dallas Independent School District. You can take several paths to learn about this tool.`,
  UI_MAP_INTRO_MODAL_TOUR: `Take a tour of the map to learn how to use it.`,
  UI_MAP_INTRO_MODAL_TOUR_BTN: `Take a tour`,
  UI_MAP_INTRO_MODAL_SEARCH: `Search for a specific school to begin in your own neighborhood.`,
  UI_MAP_INTRO_MODAL_SEARCH_BTN: `Search`,
  UI_MAP_INTRO_MODAL_FAQ: `Read our site FAQs to learn about the data sources and analytics.`,
  UI_MAP_INTRO_MODAL_FAQ_BTN: `Access FAQs`,
  UI_MAP_INTRO_MODAL_MAP: `Go straight to the map and start exploring!`,
  UI_MAP_INTRO_MODAL_MAP_BTN: `Go straight to the map!`,
}
export default en_US
