const en_US = {
  SITE_TITLE: `Site Title`,
  TEA_ID: `TEA identification number`,
  TERM_SCHOOL: `school`,
  BUTTON_VIEW_FEEDER: `Toggle feeder view`,
  BUTTON_VIEW_MAP: `Toggle map view`,
  BUTTON_MENU: `Menu`,
  BUTTON_SEARCH: `Select to search`,
  INPUT_SEARCH: `Enter search criteria`,
  INPUT_PLACEHOLDER_SEARCH: `Search... `,
  BUTTON_TOGGLE_PANEL_FILTERS: `Toggle filters panel`,
  BUTTON_TOGGLE_PANEL_WEIGHT: `Toggle weights panel`,
  BUTTON_TOGGLE_PANEL_INFO: `Toggle info panel`,
  BUTTON_SHARE_TWITTER: `Share on Twitter`,
  BUTTON_SHARE_FACEBOOK: `Share on Facebook`,
  BUTTON_SHARE_EMAIL: `Share by email`,
  BUTTON_SHARE_LINK: `Copy link`,
  UI_MAP_BUTTON_RESET_FILTER: `Reset active filter`,
  SELECT_VIEW: `Select a view`,
  SELECT_ITEM_MAP: `Map view`,
  SELECT_ITEM_FEEDER: `Feeder view`,
  UI_MAP_SR:
    'Map of Dallas, with colors showing {metric} for {quintiles}.',
  UI_MAP_RESET: `Reset map`,
  UI_MAP_CAPTURE: `Screenshot map`,
  UI_MAP_CITY: `Dallas`,
  UI_MAP_LEGEND_TITLE: `Active Metric:`,
  UI_MAP_TOGGLE_LAYERS: `TOGGLE LAYERS`,
  UI_MAP_LEGEND_SCHOOL_DOT: `School`,
  UI_MAP_LEGEND_SCHOOL_ZONE: `School zone (2 mile radius)`,
  UI_MAP_LAYERS_REDLINING: `Historical redlining`,
  UI_MAP_LAYERS_DISTRICTS: `District boundaries`,
  UI_MAP_METRIC_TITLE_CRI: `Community Resource Index`,
  UI_MAP_METRIC_ABBREV_CRI: `CRI`,
  UI_MAP_METRIC_DESC_CRI: `<p>Occaecat veniam commodo proident enim cillum exercitation consequat commodo laborum sunt. Ad voluptate reprehenderit cillum id pariatur veniam deserunt aute sunt veniam pariatur commodo laboris nulla deserunt velit.</p><p>Quis mollit ad est reprehenderit consequat velit laborum. Incididunt duis quis esse amet ad reprehenderit fugiat aliquip est magna in ea cupidatat ullamco magna tempor. Ea ullamco reprehenderit commodo ipsum aute in esse ea ea. Sunt commodo ex dolor ipsum Lorem do reprehenderit tempor adipisicing sunt laboris ex culpa elit.</p>`,
  UI_MAP_METRIC_TITLE_CRI: `Community Resource Index`,
  UI_MAP_METRIC_TITLE_ECON: `Economics`,
  UI_MAP_METRIC_TITLE_EDU: `Education`,
  UI_MAP_METRIC_TITLE_FAM: `Family`,
  UI_MAP_METRIC_TITLE_HEAL: `Health`,
  UI_MAP_METRIC_TITLE_COMM: `Community`,
  UI_MAP_METRIC_TITLE_ECON_INDEX: `Economics Index`,
  UI_MAP_METRIC_TITLE_EDU_INDEX: `Education Index`,
  UI_MAP_METRIC_TITLE_FAM_INDEX: `Family Index`,
  UI_MAP_METRIC_TITLE_HEAL_INDEX: `Health Index`,
  UI_MAP_METRIC_TITLE_COMM_INDEX: `Community Index`,
  UI_MAP_METRIC_TITLE_COMM_BBP: `Percent of households with access to broadband`,
  UI_MAP_METRIC_COMM_BVP: `Business vacancy`,
  UI_MAP_METRIC_COMM_CCTRCAP: `Community and recreation centers, estimated per 10,000`,
  UI_MAP_METRIC_COMM_INCARPCT: `Percent of adults incarcerated`,
  UI_MAP_METRIC_COMM_JUVCRIMECAP: `Juvenile-committed violent crime per 10,000 children under 18`,
  UI_MAP_METRIC_COMM_LIBCAP: `Libraries, per 10,000 population`,
  UI_MAP_METRIC_COMM_LTBVP: `Long term business vacancy`,
  UI_MAP_METRIC_COMM_LTRVP: `Long term residential vacancy`,
  UI_MAP_METRIC_COMM_OCB: `Owner-occupied households that are cost burdened`,
  UI_MAP_METRIC_COMM_OCBP: `Percent owner occupied households that are cost burdened`,
  UI_MAP_METRIC_COMM_PARKCAP: `Park areas per 10,000 population within buffer`,
  UI_MAP_METRIC_COMM_RCB: `Renter occupied households that are cost burdened`,
  UI_MAP_METRIC_COMM_RCBP: `Percent renter occupied households that are cost burdened`,
  UI_MAP_METRIC_COMM_RVP: `Residential vacancy`,
  UI_MAP_METRIC_COMM_U18BBP: `Percent of children under 18 with access to broadband`,
  UI_MAP_METRIC_ECON_CPR: `Child poverty rate`,
  UI_MAP_METRIC_ECON_FINCAP: `Banks and credit unions per 10,000 persons`,
  UI_MAP_METRIC_ECON_MEDINC: `Median household income`,
  UI_MAP_METRIC_ECON_PAYDAYCAP: `Payday lending and cash advance businesses per 10,000 persons`,
  UI_MAP_METRIC_ECON_PCTLWJOBS: `Percent of jobs earning less than $1,500 a month`,
  UI_MAP_METRIC_ECON_PCTMWJOBS: `Percent of jobs earning wages between $1,500 and $3,333 a month`,
  UI_MAP_METRIC_ECON_PR: `Povery rate`,
  UI_MAP_METRIC_ECON_PYR: `Unemployment rate of 16- to 24-year-olds`,
  UI_MAP_METRIC_ECON_UR: `Unemployment rate`,
  UI_MAP_METRIC_EDU_OOSTKIDS: `Number of afterschool program seats relative to number of children`,
  UI_MAP_METRIC_EDU_PERBACH: `Percent of population with a bachelor's degree or higher`,
  UI_MAP_METRIC_EDU_PEREARLYED: `Percent of children 3 and 4 enrolled in school`,
  UI_MAP_METRIC_EDU_QECKIDS: `Number of high quality early childcare seats per child`,
  UI_MAP_METRIC_FAM_AFFCCKIDS: `Licensed, affordable child care centers relative to number of children`,
  UI_MAP_METRIC_FAM_LCCKIDS: `Licensed child care centers relative to children`,
  UI_MAP_METRIC_FAM_TPHH: `Two-parent households`,
  UI_MAP_METRIC_FAM_TPHHPCT: `Percent of households with children that are two-parent`,
  UI_MAP_METRIC_HEL_BPHIGH: `Adults with high blood pressure, estimated per 10,000 `,
  UI_MAP_METRIC_HEL_CASTTHMA: `Adults with asthma, estimated per 10,000`,
  UI_MAP_METRIC_HEL_CHECKUP: `Adult routine checkup doctor visits in the past year, estimated per 10,000`,
  UI_MAP_METRIC_HEL_FRUITSVEGGIES: `Combined spending on fresh fruits and vegetables`,
  UI_MAP_METRIC_HEL_LE: `Average life expectancy`,
  UI_MAP_METRIC_HEL_MHLTH: `Adults with poor mental health for days or more, estimated per 10,000`,
  UI_MAP_METRIC_HEL_OBESITY: `Adult obesity, estimated per 10,000`,
  UI_MAP_METRIC_HEL_PERPRI: `Percent of population with private insurance`,
  UI_MAP_METRIC_HEL_PERPUB: `Percent of population with public insurance`,
  UI_MAP_METRIC_HEL_PHARMACAP: `Licensed pharmacies per 10,000 population`,
  UI_MAP_METRIC_HEL_PHLTH: `Adults with poor physical health, estimated per 10,000`,
  UI_MAP_METRIC_HEL_SLEEP: `Adults sleeping less than 7 hours per night, estimated per 10,000 population`,
  UI_MAP_METRIC_HEL_STROKE: `Adults who have had a stroke, estimated per 10,000`,
  UI_FEEDER_TITLE_FEEDER_CHART: `Dallas ISD School Feeder Patterns`,
  UI_FEEDER_TITLE_FEEDER_DESC: `<p>A feeder pattern is the sequence of schools a student attends as they advance from grade to grade, based on their residing address.</p><p>The first chart shows each feeder pattern’s average Community Resource Index on a scale from 0-100.</p><p>The second chart shows the distribution of campuses across the range of the Community Resource Index.</p><p>Hover and click within the charts to see more data about each feeder pattern and its schools. You can also use the search bar to find a school and highlight its feeder pattern and campus.</p>`,
  UI_FEEDER_TITLE_SCHOOLS_CHART: `Distribution of campuses across CRI`,
  UI_FEEDER_TOOLTIP_INDEX_DESC: `*Index scores measured 0 to 100`,
  UI_FEEDER_TOOLTIP_SUBINDEX_AVG: `Average {metric} index score:`,
  UI_FEEDER_FEEDER_CHART_DESC: `Bar chart indicating average CRI for each feeder in Dallas ISD.`,
  UI_FEEDER_SCHOOL_CHART_DESC: `Scatterplot chart indicating number of schools with a given CRI value. Schools are highlighted when their feeder is hovered in the feeder chart.`,
  UI_MAP_TOOLTIP_FEEDER: `{name} Schools`,
  TERM_INDEX_AVERAGE: `Index Average`,
  TERM_PLURAL: `{term}s`,

  // UI_MAP_METRIC_TITLE_COMM_CRIMEDENSITY: `Density of part a crimes`,
  // UI_MAP_METRIC_TITLE_COMM_CRIME: `Count of part a crimes`,
  // UI_MAP_METRIC_TITLE_COMM_CHURCH: `Count of churches `,
  // UI_MAP_METRIC_COMM_CHURCHDENSITY: `Density of churches`,
  // UI_MAP_METRIC_COMM_EV1: `Eviction filings`,
  // UI_MAP_METRIC_COMM_EV2: `Eviction removals`,
  // UI_MAP_METRIC_COMM_EV3: `Eviction filing rate`,
  // UI_MAP_METRIC_COMM_EV4: `Eviction rate`,
  // UI_MAP_METRIC_COMM_RVP: `Residential vacancy`,
  //
  // UI_MAP_METRIC_COMM_LTVP: `Long term residential vacancy`,
  // UI_MAP_METRIC_COMM_LTBVP: `Long term business vacancy`,
  // UI_MAP_METRIC_COMM_NSRES: `No-stat residential`,
  // UI_MAP_METRIC_COMM_NSBUS: `No-stat business`,
  // UI_MAP_METRIC_COMM_NSRESLT: `No-stat long term residential`,
  // UI_MAP_METRIC_COMM_NSBUSLT: `No-stat long term business`,
  // UI_MAP_METRIC_COMM_THH: `Total households`,
  // UI_MAP_METRIC_COMM_OOHH: `Owner occupied households`,
  // UI_MAP_METRIC_COMM_ROHH: `Renter occupied households`,
  // UI_MAP_METRIC_COMM_OCB: `Owner occupied households that are cost burdened`,
  // UI_MAP_METRIC_COMM_RCB: `Renter occupied households that are cost burdened`,
  // UI_MAP_METRIC_COMM_OCBP: `Percent owner occupied households that are cost burdened - mean of tract value`,
  // UI_MAP_METRIC_COMM_RCBP: `Percent renter occupied households that are cost burdened - mean of tract value`,
  // UI_MAP_METRIC_COMM_OWNCB_PCT: `Percent owner occupied households that are cost burdened - calculated from buffer totals`,
  // UI_MAP_METRIC_COMM_RENTCB_PCT: `Percent renter occupied households that are cost burdened - calculated from buffer totals`,
  // UI_MAP_METRIC_COMM_ADUINCAR_DENOM: `Total adults in zip codes from commit incarceration data`,
  // UI_MAP_METRIC_COMM_ADUINCARCT: `Total count of incarcerated adults per zip, derived from commit data`,
  // UI_MAP_METRIC_COMM_INCARPCT: `Percent of adults incracerated derived from comm_aduincar_denom and comm_aduincarct`,
  // UI_MAP_METRIC_COMM_PCTVOIP: `Percent of households with voip`,
  // UI_MAP_METRIC_COMM_PCTWIFI: `Percent of household with wifi`,
  // UI_MAP_METRIC_ECON_ADUPOP: `Population for unemployment denominator`,
  // UI_MAP_METRIC_ECON_UNEM: `Estimate of population that is unemployed`,
  // UI_MAP_METRIC_ECON_JUVPOP: `Population 16-24`,
  // UI_MAP_METRIC_ECON_JUVUNEM: `Population 16-24 unemployed and not in school`,
  // UI_MAP_METRIC_ECON_UNEMPPCT: `Unemployment rate`,
  // UI_MAP_METRIC_ECON_JUVUNEMPPCT: `Unemployment rate of population 16-24`,
  // UI_MAP_METRIC_ECON_MEDINC: `Median income`,
  // UI_MAP_METRIC_ECON_JOBS17: `Total jobs in 2017`,
  // UI_MAP_METRIC_ECON_BANKS: `Number of banks`,
  // UI_MAP_METRIC_ECON_CU: `Number of credit unions`,
  // UI_MAP_METRIC_ECON_FIN: `Number of banks + credit unions`,
  // UI_MAP_METRIC_ECON_PAYDAY: `Number of payday lending and cash advance`,
  // UI_MAP_METRIC_ECON_POP: `Population for poverty measures`,
  // UI_MAP_METRIC_ECON_BELPOV: `Population below poverty`,
  // UI_MAP_METRIC_ECON_KIDS: `Child population (under 18)`,
  // UI_MAP_METRIC_ECON_CBP: `Population under 18 below poverty`,
  // UI_MAP_METRIC_ECON_U5: `Children under 5 years old`,
  // UI_MAP_METRIC_ECON_U5BP: `Children under 5 below poverty`,
  // UI_MAP_METRIC_ECON_5T17: `Children 5 to 17 population`,
  // UI_MAP_METRIC_ECON_5T17BP: `Children 5 to 17 below poverty`,
  // UI_MAP_METRIC_ECON_BPPCT: `Poverty rate - mean of tract data in buffer`,
  // UI_MAP_METRIC_ECON_CPR: `Child poverty rate - mean of tract data in buffer`,
  // UI_MAP_METRIC_ECON_U5RBP: `Povery rate for kids under5 - mean of tract data in buffer`,
  // UI_MAP_METRIC_ECON_5T17RBP: `Poverty rate for kids 5 to 17 - mean of tract data in buffer`,
  // UI_MAP_METRIC_ECON_POVERTYRATE: `Povery rate - derived from tract sums in buffer`,
  // UI_MAP_METRIC_ECON_CPR2: `Child poverty rate - derive from tract sums in buffer`,
  // UI_MAP_METRIC_ECON_U5_POVRATE: `U5 poverty rate - derived from tract sums in buffer`,
  // UI_MAP_METRIC_ECON_ECON_5T17_POVRATE: `5 to 17 poverty rate - derived from tract sums in buffer`,
  // UI_MAP_METRIC_ECON_EDU_POPADU: `Population 25+`,
  // UI_MAP_METRIC_EDU_BACH: `Pop 25+ w/ bachelors degree or higher`,
  // UI_MAP_METRIC_EDU_K34: `Children aged 3 and 4`,
  // UI_MAP_METRIC_EDU_K34ES: `Children aged 3 and 4 enrolled in school`,
  // UI_MAP_METRIC_EDU_PERBACH: `Percent of population with bach or higher - derived form tract sums`,
  // UI_MAP_METRIC_EDU_PEREARLYED: `Percent of children 3 and 4 enrolled in school - derived from tract sums`,
  // UI_MAP_METRIC_EDU_OOSTCT: `Number of afterschool programs in buffer`,
  // UI_MAP_METRIC_EDU_OOSTCAP: `Total capacity of afterschool program seats in buffer`,
  // UI_MAP_METRIC_EDU_OOSTCAPMEAN: `Mean capacity of afterschool program seat in buffer`,
  // UI_MAP_METRIC_FAM_HHC: `Households with children`,
  // UI_MAP_METRIC_FAM_HHCFH: `Households with children and female householder no husband`,
  // UI_MAP_METRIC_FAM_HHCMH: `Households with children and male householder no wife`,
  // UI_MAP_METRIC_FAM_LCC: `Licensed child care centers in buffer`,
  // UI_MAP_METRIC_FAM_TPHH: `Two parent households = hhc - (hhcmh + hhcfh)`,
  // UI_MAP_METRIC_FAM_TPHH_PCT: `Percent of households with children that are two parent`,
  // UI_MAP_METRIC_HEL_PHARM: `Licensed pharmacies in buffer`,
  // UI_MAP_METRIC_HEL_CLIN: `Clinics in buffer`,
  // UI_MAP_METRIC_HEL_INSPOP: `Insured population denominator`,
  // UI_MAP_METRIC_HEL_UNINS: `Population that is uninsured`,
  // UI_MAP_METRIC_HEL_PERINS: `Percent of population that is insured - derived from tract sums`,
  // UI_MAP_METRIC_HEL_GROC: `Grocery stores in buffer`,
  // UI_MAP_METRIC_HEL_LE: `Average life expectancy`,
  // UI_MAP_METRIC_HEL_FRUITAVG: `Average household spending on fresh fruit`,
  // UI_MAP_METRIC_HEL_VEGAVG: `Average household spending on fresh vegetables`,
  UI_MAP_PANEL_SELECT: `Select filter category...`,
  UI_MAP_PANEL_SELECT_QUINTILE: `Select quintile`,
  UI_MAP_PANEL_QUINTILE_0: `First quintile`,
  UI_MAP_PANEL_QUINTILE_1: `Second quintile`,
  UI_MAP_PANEL_QUINTILE_2: `Third quintile`,
  UI_MAP_PANEL_QUINTILE_3: `Fourth quintile`,
  UI_MAP_PANEL_QUINTILE_4: `Fifth quintile`,
  UI_MAP_PANEL_QUINTILE_ENABLE: `Enable {quintile} quintile`,
  UI_MAP_PANEL_QUINTILE_DISABLE: `Disable {quintile} quintile`,
  UI_MAP_PANEL_METRIC_ENABLE: `Enable metric {metric}`,
  UI_MAP_PANEL_METRIC_DISABLE: `Disable metric {metric}`,
  FIRST: `first`,
  SECOND: `second`,
  THIRD: `third`,
  FOURTH: `fourth`,
  FIFTH: `fifth`,
  ALL_FIVE: `all five`,
  QUINTILE: `quintile`,
  QUINTILES: `quintiles`,
  NO: `no`,
  AND: `and`,
}
export default en_US
