import LANG from './en'
import {
  CRI_COLORS,
  ECON_COLORS,
  EDU_COLORS,
  FAM_COLORS,
  HEAL_COLORS,
  COMM_COLORS,
} from './colors'

export const CPAL_METRICS = [
  {
    id: 'cri',
    title: 'UI_MAP_METRIC_TITLE_CRI',
    abbrev: 'CRI',
    range: [0, 100],
    colors: CRI_COLORS,
    tab: 'cri',
    tab_level: 0,
    tooltip: 1,
  },
  {
    id: 'econ_index',
    title: 'UI_MAP_METRIC_TITLE_ECON',
    abbrev: 'ECON',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 0,
    tooltip: 1,
  },
  {
    id: 'edu_index',
    title: 'UI_MAP_METRIC_TITLE_EDU',
    abbrev: 'EDU',
    range: [0, 100],
    colors: EDU_COLORS,
    tab: 'edu',
    tab_level: 0,
    tooltip: 1,
  },
  {
    id: 'fam_index',
    title: 'UI_MAP_METRIC_TITLE_FAM',
    abbrev: 'FAM',
    range: [0, 100],
    colors: FAM_COLORS,
    tab: 'fam',
    tab_level: 0,
    tooltip: 1,
  },
  {
    id: 'health_index',
    title: 'UI_MAP_METRIC_TITLE_HEAL',
    abbrev: 'HEAL',
    range: [0, 100],
    colors: HEAL_COLORS,
    tab: 'hel',
    tab_level: 0,
    tooltip: 1,
  },
  {
    id: 'com_index',
    title: 'UI_MAP_METRIC_TITLE_COMM',
    abbrev: 'COMM',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 0,
    tooltip: 1,
  },
  {
    id: 'comm_crimedensity',
    title: 'UI_MAP_METRIC_TITLE_COMM_CRIMEDENSITY',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_crime',
    title: 'UI_MAP_METRIC_TITLE_COMM_CRIME',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_church',
    title: 'UI_MAP_METRIC_TITLE_COMM_CHURCH',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_churchdensity',
    title: 'UI_MAP_METRIC_COMM_CHURCHDENSITY',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_ev1',
    title: 'UI_MAP_METRIC_COMM_EV1',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_ev2',
    title: 'UI_MAP_METRIC_COMM_EV2',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_ev3',
    title: 'UI_MAP_METRIC_COMM_EV3',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_ev4',
    title: 'UI_MAP_METRIC_COMM_EV4',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_rvp',
    title: 'UI_MAP_METRIC_COMM_RVP',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_bvp',
    title: 'UI_MAP_METRIC_COMM_BVP',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_ltrvp',
    title: 'UI_MAP_METRIC_COMM_LTVP',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_ltbvp',
    title: 'UI_MAP_METRIC_COMM_LTBVP',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_nsres',
    title: 'UI_MAP_METRIC_COMM_NSRES',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_nsbus',
    title: 'UI_MAP_METRIC_COMM_NSBUS',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_nsreslt',
    title: 'UI_MAP_METRIC_COMM_NSRESLT',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_nsbuslt',
    title: 'UI_MAP_METRIC_COMM_NSBUSLT',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_thh',
    title: 'UI_MAP_METRIC_COMM_THH',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_oohh',
    title: 'UI_MAP_METRIC_COMM_OOHH',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_rohh',
    title: 'UI_MAP_METRIC_COMM_ROHH',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_ocb',
    title: 'UI_MAP_METRIC_COMM_OCB',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_rcb',
    title: 'UI_MAP_METRIC_COMM_RCB',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
    tooltip: 0,
  },
  {
    id: 'comm_ocbp',
    title: 'UI_MAP_METRIC_COMM_OCBP',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
  },
  {
    id: 'comm_rcbp',
    title: 'UI_MAP_METRIC_COMM_RCBP',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
  },
  {
    id: 'comm_owncb_pct',
    title: 'UI_MAP_METRIC_COMM_OWNCB_PCT',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
  },
  {
    id: 'comm_rentcb_pct',
    title: 'UI_MAP_METRIC_COMM_RENTCB_PCT',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
  },
  {
    id: 'comm_aduincar_denom',
    title: 'UI_MAP_METRIC_COMM_ADUINCAR_DENOM',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
  },
  {
    id: 'comm_aduincarct',
    title: 'UI_MAP_METRIC_COMM_ADUINCARCT',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
  },
  {
    id: 'comm_incarpct',
    title: 'UI_MAP_METRIC_COMM_INCARPCT',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
  },
  {
    id: 'comm_pctvoip',
    title: 'UI_MAP_METRIC_COMM_PCTVOIP',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
  },
  {
    id: 'comm_pctwifi',
    title: 'UI_MAP_METRIC_COMM_PCTWIFI',
    abbrev: '',
    range: [0, 100],
    colors: COMM_COLORS,
    tab: 'comm',
    tab_level: 1,
  },
  {
    id: 'econ_adupop',
    title: 'UI_MAP_METRIC_ECON_ADUPOP',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_unem',
    title: 'UI_MAP_METRIC_ECON_UNEM',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_juvpop',
    title: 'UI_MAP_METRIC_ECON_JUVPOP',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_juvunem',
    title: 'UI_MAP_METRIC_ECON_JUVUNEM',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_unemppct',
    title: 'UI_MAP_METRIC_ECON_UNEMPPCT',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_juvunemppct',
    title: 'UI_MAP_METRIC_ECON_JUVUNEMPPCT',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_medinc',
    title: 'UI_MAP_METRIC_ECON_MEDINC',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_jobs17',
    title: 'UI_MAP_METRIC_ECON_JOBS17',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_banks',
    title: 'UI_MAP_METRIC_ECON_BANKS',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_cu',
    title: 'UI_MAP_METRIC_ECON_CU',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_fin',
    title: 'UI_MAP_METRIC_ECON_FIN',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_payday',
    title: 'UI_MAP_METRIC_ECON_PAYDAY',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_pop',
    title: 'UI_MAP_METRIC_ECON_POP',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_belpov',
    title: 'UI_MAP_METRIC_ECON_BELPOV',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_kids',
    title: 'UI_MAP_METRIC_ECON_KIDS',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_cbp',
    title: 'UI_MAP_METRIC_ECON_CBP',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_u5',
    title: 'UI_MAP_METRIC_ECON_U5',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_u5bp',
    title: 'UI_MAP_METRIC_ECON_U5BP',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_5t17',
    title: 'UI_MAP_METRIC_ECON_5T17',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_5t17bp',
    title: 'UI_MAP_METRIC_ECON_5T17BP',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_bppct',
    title: 'UI_MAP_METRIC_ECON_BPPCT',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_cpr',
    title: 'UI_MAP_METRIC_ECON_CPR',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_u5rbp',
    title: 'UI_MAP_METRIC_ECON_U5RBP',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_5t17rbp',
    title: 'UI_MAP_METRIC_ECON_5T17RBP',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_povertyrate',
    title: 'UI_MAP_METRIC_ECON_POVERTYRATE',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_cpr2',
    title: 'UI_MAP_METRIC_ECON_CPR2',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_u5_povrate',
    title: 'UI_MAP_METRIC_ECON_U5_POVRATE',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'econ_5t17_povrate',
    title: 'UI_MAP_METRIC_ECON_ECON_5T17_POVRATE',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'econ',
    tab_level: 1,
  },
  {
    id: 'fam_hhc',
    title: 'UI_MAP_METRIC_FAM_HHC',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'fam',
    tab_level: 1,
  },
  {
    id: 'fam_hhcfh',
    title: 'UI_MAP_METRIC_FAM_HHCFH',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'fam',
    tab_level: 1,
  },
  {
    id: 'fam_hhcmh',
    title: 'UI_MAP_METRIC_FAM_HHCMH',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'fam',
    tab_level: 1,
  },
  {
    id: 'fam_lcc',
    title: 'UI_MAP_METRIC_FAM_LCC',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'fam',
    tab_level: 1,
  },
  {
    id: 'fam_tphh',
    title: 'UI_MAP_METRIC_FAM_TPHH',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'fam',
    tab_level: 1,
  },
  {
    id: 'fam_tphh_pct',
    title: 'UI_MAP_METRIC_FAM_TPHH_PCT',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'fam',
    tab_level: 1,
  },
  {
    id: 'edu_bach',
    title: 'UI_MAP_METRIC_EDU_BACH',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'edu',
    tab_level: 1,
  },
  {
    id: 'edu_k34',
    title: 'UI_MAP_METRIC_EDU_K34',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'edu',
    tab_level: 1,
  },
  {
    id: 'edu_k34es',
    title: 'UI_MAP_METRIC_EDU_K34ES',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'edu',
    tab_level: 1,
  },
  {
    id: 'edu_oostcap',
    title: 'UI_MAP_METRIC_EDU_OOSTCAP',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'edu',
    tab_level: 1,
  },
  {
    id: 'edu_oostcapmean',
    title: 'UI_MAP_METRIC_EDU_OOSTCAPMEAN',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'edu',
    tab_level: 1,
  },
  {
    id: 'edu_oostct',
    title: 'UI_MAP_METRIC_EDU_OOSTCT',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'edu',
    tab_level: 1,
  },
  {
    id: 'edu_perbach',
    title: 'UI_MAP_METRIC_EDU_PERBACH',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'edu',
    tab_level: 1,
  },
  {
    id: 'edu_perearlyed',
    title: 'UI_MAP_METRIC_EDU_PEREARLYED',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'edu',
    tab_level: 1,
  },
  {
    id: 'edu_popadu',
    title: 'UI_MAP_METRIC_ECON_EDU_POPADU',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'edu',
    tab_level: 1,
  },
  {
    id: 'hel_clin',
    title: 'UI_MAP_METRIC_HEL_CLIN',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'hel',
    tab_level: 1,
  },
  {
    id: 'hel_fruitavg',
    title: 'UI_MAP_METRIC_HEL_FRUITAVG',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'hel',
    tab_level: 1,
  },
  {
    id: 'hel_groc',
    title: 'UI_MAP_METRIC_HEL_GROC',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'hel',
    tab_level: 1,
  },
  {
    id: 'hel_inspop',
    title: 'UI_MAP_METRIC_HEL_INSPOP',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'hel',
    tab_level: 1,
  },
  {
    id: 'hel_le',
    title: 'UI_MAP_METRIC_HEL_LE',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'hel',
    tab_level: 1,
  },
  {
    id: 'hel_perins',
    title: 'UI_MAP_METRIC_HEL_PERINS',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'hel',
    tab_level: 1,
  },
  {
    id: 'hel_pharm',
    title: 'UI_MAP_METRIC_HEL_PHARM',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'hel',
    tab_level: 1,
  },
  {
    id: 'hel_unins',
    title: 'UI_MAP_METRIC_HEL_UNINS',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'hel',
    tab_level: 1,
  },
  {
    id: 'hel_vegavg',
    title: 'UI_MAP_METRIC_HEL_VEGAVG',
    abbrev: '',
    range: [0, 100],
    colors: ECON_COLORS,
    tab: 'hel',
    tab_level: 1,
  },
]

/**
 * Data metrics in the SEDA data set
 */
export const METRICS = [
  {
    id: 'avg',
    label: LANG['LABEL_AVG'],
    range: {
      'map_*_gap': [-6, 6],
      map_counties: [-3, 3],
      map_districts: [-3.5, 3.5],
      map_schools: [-5, 5],
      '*_counties_np': [-4, 3],
      '*_counties_wh': [-1.5, 4.5],
      '*_districts_wh': [-1.5, 5],
      '*_*_gap': [-0.5, 5],
      '*_counties_b': [-4, 2],
      '*_counties_w': [-4, 4],
      '*_counties_a': [-4, 5],
      '*_counties': [-4.5, 2.5],

      '*_districts_b': [-4, 3],
      '*_districts_w': [-4, 4],
      '*_districts_a': [-4, 5],
      '*_districts': [-4.5, 4.5],
      '*_schools': [-8, 7],
    },
    map: true,
    scatterplot: true,
  },
  {
    id: 'cri',
    label: LANG['LABEL_AVG'],
    range: {
      'map_*_gap': [-6, 6],
      map_counties: [-3, 3],
      map_districts: [-3.5, 3.5],
      map_schools: [0, 100],
      '*_counties_np': [-4, 3],
      '*_counties_wh': [-1.5, 4.5],
      '*_districts_wh': [-1.5, 5],
      '*_*_gap': [-0.5, 5],
      '*_counties_b': [-4, 2],
      '*_counties_w': [-4, 4],
      '*_counties_a': [-4, 5],
      '*_counties': [-4.5, 2.5],

      '*_districts_b': [-4, 3],
      '*_districts_w': [-4, 4],
      '*_districts_a': [-4, 5],
      '*_districts': [-4.5, 4.5],
      '*_schools': [-8, 7],
    },
    map: true,
    scatterplot: false,
  },
  {
    id: 'grd',
    label: LANG['LABEL_GRD'],
    range: {
      'map_*_gap': [-0.4, 0.4],
      'map_*_*': [0.5, 1.5],
      '*_schools': [-0.2, 2.6],
      '*_*_b': [0.4, 1.4],
      '*_*_wb': [-0.3, 0.45],
      '*_*_gap': [-0.4, 0.4],
      '*': [0.4, 1.6],
    },
    map: true,
    scatterplot: true,
  },
  {
    id: 'coh',
    label: LANG['LABEL_COH'],
    range: {
      'map_*_*': [-0.333, 0.3333],
      '*_*_gap': [-0.25, 0.25],
      '*_schools': [-1, 1],
      '*': [-0.5, 0.5],
    },
    map: true,
    scatterplot: true,
  },
  {
    id: 'ses',
    label: LANG['LABEL_SES_NO_REGION'],
    map: false,
    scatterplot: true,
    range: {
      '*_districts_h': [-5, 3],
      '*_counties_h': [-4, 2],
      '*_*_b': [-6, 2],
      '*_*_h': [-6, 2],
      '*_districts_wb': [-1, 6],
      '*_*_wb': [0, 5],
      '*_districts_wh': [-1, 5],
      '*_*_wh': [-0.5, 4.5],
      'map_*_*': [-3, 3],
      '*_counties': [-4, 3],
      '*_districts_w': [-3, 3],
      '*_districts': [-5, 3],
      '*': [-5, 4],
    },
  },
  {
    id: 'seg',
    label: LANG['LABEL_SEG'],
    range: {
      '*_*_np': [0, 0.75],
      '*': [-0.25, 0.75],
    },
    map: false,
    scatterplot: true,
  },
  {
    id: 'min',
    label: LANG['LABEL_MIN'],
    range: {
      '*': [-0.1, 0.7],
    },
  },
  {
    id: 'frl',
    label: LANG['LABEL_FRL'],
    range: {
      '*': [0, 1],
    },
    map: false,
    scatterplot: true,
  },
]

export const KEY_METRIC_IDS = ['cri', 'avg', 'grd', 'coh']
